### ISSUE TITLE
SpatRaster error in enmtools.maxent()

### ISSUE THREAD

**Issue by ascanioalfredoa** [danlwarren/ENMTools#235]
Hi Dan. Hope you are doing well.

I'm finding an issue with the current version of ENMTools that the example is able to replicate. If I run a maxent model using a SpatRaster environmental dataset

`try(enmtools.maxent(iberolacerta.clade$species$monticola, env = euro.worldclim))`

Returns the following error:

>Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘maxent’ for signature ‘"SpatRaster", "data.frame"’

I see that the issue comes from dismo::maxent(), which requires the _env_ object to be a rasterlayer or rasterstack (already tested it and it runs). However, if I try converting the SpatRaster into a RasterStack and pass it to the enmtools.maxent() tool I get:

`try(enmtools.maxent(iberolacerta.clade$species$monticola, env = raster::stack(euro.worldclim)))`

>Error : [compareGeom] SRS do not match
In addition: Warning message:
In check.raster(env, "env") :
  env is not the expected SpatRaster class (instead, it is of class RasterStack). ENMTools will attempt to coerce using terra::rast(...), but we cannot guaranteed the correctness of the result. Please consider using SpatRaster format directly in the future, to minimize unexpected results.

For dismo, something like this seems to be working

`dismo::maxent(raster::stack(euro.worldclim), p = crds(iberolacerta.clade$species$monticola$presence.points))`

**Comment by danlwarren** [comment]
Thank you for the feedback!  This is all new functionality so we're still ironing the kinks out.  Just out of curiosity, in the second example is it returning a model despite complaining?

**Comment by stiatragul** [comment]
Hey Dan, thanks for developing this great package. And thanks @ascanioalfredoa for raising the issue.
I wanted to point out that when trying to run maxent in `enmtools.aoc()` I got the same error. I am using a slightly different example, still from the code you provided using GBIF and anoles where 
`brev.clade` is a list of objects from your custom function `species.from.gbif()`
and
```
hisp.env <- worldclim_global(var='bio', res=10, path = "./")
hisp.env <- crop(hisp.env, extent(-75, -65, 16, 21))
```

Command:
`R> enmtools.aoc(clade = brev.clade,  env = hisp.env, nreps = 50, overlap.source = "mx")` 

Output:
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘maxent’ for signature ‘"SpatRaster", "data.frame"’
```

I was able to run maxent in dismo directly with raster::stack(hisp.env) although that only 
`dismo::maxent(raster::stack(hisp.env), p = crds(brev.clade$species[[5]]$presence.points))`

Thanks again for your attention

**Comment by danlwarren** [comment]
That makes sense - down the line it's still just calling the enmtools.maxent function.  We tried to have it convert to something dismo::maxent() would understand on the fly, but clearly we weren't fully successful in that.  We'll try to get a fix ASAP.  Thanks!

**Comment by ascanioalfredoa** [comment]
> Thank you for the feedback! This is all new functionality so we're still ironing the kinks out. Just out of curiosity, in the second example is it returning a model despite complaining?

Sorry, I meant that I was able to run the dismo::maxent() with a rasterstack, but not with a SpatRaster. Trying to do the SpatRaster prompted the errors I copied above. My temporary fix was to create a enmtools.maxent2() function where I used raster::stack(env) inside the dismo::maxent() calls. And then used the updates function inside the other enmtools tests I needed. With that change, everything ran smoothly.

**Comment by danlwarren** [comment]
@rdinnager has just made an update to the master branch that should fix this - can you try it and see if it works for you?

**Comment by bloomer3** [comment]
Hello! I have been having the same issue. I downloaded the latest 'develop' version of ENMTools to try the fix. 

For the develop version of enmtools.maxent, the species presence points have to be in a data frame (I just used read.csv) and 'env' has to be a RasterStack. The SpatRaster and SpatVector don't work with the update. 

When running enmtools.maxent, it started but I eventually got the error:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘raster’ for signature ‘"numeric"’

Not sure where it has gone wrong, any insight to next steps to try would be great.

**Comment by rdinnager** [comment]
Hi @bloomer3,

Do you mean that you installed `ENMTools` from the `develop` branch on github? If so, please install from the `master` branch, as this is the official development version of `ENMTools` (the release version is on CRAN). The `develop` branch is for internal development purposes and isn't necessarily kept in a working state. If you still have a problem after installing from `master`, please let us know.

**Comment by bloomer3** [comment]
Hi @rdinnager 

Thanks for the quick reply. 
I have reinstalled from the master branch and am still getting the same error:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘raster’ for signature ‘"numeric"’

My 'env' are in SpatRaster format, and my presence and background points are SpatVectors.

**Comment by rdinnager** [comment]
Okay, would you be able to make a minimal reproducible example? If you don't know how to do that, could you at least paste the code you ran before you got this error (including everything before `enmtools.maxent()`)? Also, after you get the error, can you run `traceback()` and then paste the results here?

**Comment by bloomer3** [comment]
[enmtools_code.txt](https://github.com/danlwarren/ENMTools/files/11151522/enmtools_code.txt)
[traceback.txt](https://github.com/danlwarren/ENMTools/files/11151546/traceback.txt)

Hi @rdinnager 
Attached are text files for my current code and the traceback error message. 

Thanks!

**Comment by ascanioalfredoa** [comment]
Hi everyone. For me the enmtools.maxent is now running. I didn't have a chance to try with my own data, but the example code is running without any issues now

`try(enmtools.maxent(iberolacerta.clade$species$monticola, env = euro.worldclim))`

Thanks for the quick fix!

**Comment by ascanioalfredoa** [comment]
> [enmtools_code.txt](https://github.com/danlwarren/ENMTools/files/11151522/enmtools_code.txt) [traceback.txt](https://github.com/danlwarren/ENMTools/files/11151546/traceback.txt)
> 
> Hi @rdinnager Attached are text files for my current code and the traceback error message.
> 
> Thanks!

Hi @bloomer3. I think one issue may be that one of your rasters is converted to factor before stacking, but there is no indication of which variable it is in the maxent line. If you check the help for dismo::maxent, it has an argument called _factors_, so you should add that to your code and see if it runs

`fodiens.mx<-enmtools.maxent(fodiens,env,test.prop=0.25,args=my.args.mt, env.nback=10000, verbose=TRUE, factors = "nlcd)`

**Comment by dibamus** [comment]
I am having this issue specifically when asking maxent to perform replicate testing. the general pattern here is:

`enmtools.maxent(fodiens, env.spatRaster, test.prop = 0.3, path = "subfolder_of_wd, args = c("replicates=3")`

this yields the error
`Error: unable to find an inherited method for function ‘raster’ for signature ‘x = "numeric"’`

If I switch the number of replicates to 1, the same line works - no error.

using dismo only, I can run replicates successfully

`dismo::maxent(env.RasterStack, p = observations.df, nbg=5000. path = "subfolder_of_wd, args = c("replicates=3")`

**Comment by danlwarren** [comment]
I'm on holiday until next week, but just real quick I think this is because we just haven't set ENMTools up to work with multiple replicates through Maxent. After building the model, ENMTools collects the suitability raster and shoves it into an enmtools.model object along with a bunch of other stuff (summary stats, plots, etc.).  When there are multiple outputs it's just not finding what it expects to.  

Are you just trying to get a mean and variance raster for a set of bootstrap replicates?  If so I could probably bash together some code to allow you to do that.

**Comment by dibamus** [comment]
Thanks for the quick reply - in my case I am using the maxent replicates to select a median or mean model from the distribution. I am pretty new to SDMs but decent enough with R that I think I can write up what I need here since my use case is out of bounds. I just figured I'd raise the issue here since I hadn't seen documentation of other users with this problem. Enjoy your holiday!
